---
sidebar: sidebar 
permalink: data-analytics/kafka-rebalance.html 
keywords: rebalance, test, self balancing, brokers 
summary: 该测试基于自平衡集群功能，该功能可根据集群拓扑变化或不均匀负载自动重新平衡。 
---
= 融合自平衡集群
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
如果您以前管理过 Kafka 集群，那么您可能熟悉手动将分区重新分配给不同代理以确保整个集群的工作负载平衡所带来的挑战。对于部署大量 Kafka 的组织来说，重新整理大量数据可能是一项艰巨、繁琐且有风险的任务，尤其是在集群之上构建关键任务应用程序时。然而，即使对于最小的 Kafka 用例，该过程也很耗时并且容易出现人为错误。

在我们的实验室中，我们测试了 Confluent 自平衡集群功能，该功能可以根据集群拓扑变化或不均匀负载自动重新平衡。 Confluent 重新平衡测试有助于测量当节点发生故障或扩展节点需要在代理之间重新平衡数据时添加新代理的时间。在经典的 Kafka 配置中，需要重新平衡的数据量会随着集群的增长而增长，但是在分层存储中，重新平衡仅限于少量数据。根据我们的验证，在经典的 Kafka 架构中，分层存储中的重新平衡需要几秒或几分钟，并且随着集群的增长而线性增长。

在自平衡集群中，分区重新平衡完全自动化，以优化 Kafka 的吞吐量，加速代理扩展，并减少运行大型集群的运营负担。在稳定状态下，自平衡集群监控代理之间的数据偏差，并不断重新分配分区以优化集群性能。当扩大或缩小平台规模时，自平衡集群会自动识别新代理的存在或旧代理的删除，并触发后续分区重新分配。这使您能够轻松地添加和停用代理，从而使您的 Kafka 集群从根本上更加有弹性。这些好处不需要任何人工干预、复杂的数学运算或分区重新分配通常带来的人为错误风险。因此，数据重新平衡可以在更短的时间内完成，您可以自由地专注于更高价值的事件流项目，而不需要不断监督您的集群。

Instaclustr 还支持自我再平衡功能，并且已为多个客户实施。
