---
sidebar: sidebar 
permalink: software/ai-conf-protopia-usecases.html 
keywords: environmental intelligence, edge device wearables, noncombatant evacuation operations, cloud migration of analytics 
summary: 数字图像处理具有许多优点，使许多组织能够充分利用与视觉表示相关的数据。 NetApp和 Protopia 解决方案提供了独特的 AI 推理设计，以在整个 ML/DL 生命周期中保护和私有化 AI/ML 数据。它使客户能够保留敏感数据的所有权，通过缓解与隐私相关的担忧，使用公共或混合云部署模型实现规模和效率，并在边缘部署人工智能推理。 
---
= 解决方案领域
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
数字图像处理具有许多优点，使许多组织能够充分利用与视觉表示相关的数据。 NetApp和 Protopia 解决方案提供了独特的 AI 推理设计，以在整个 ML/DL 生命周期中保护和私有化 AI/ML 数据。它使客户能够保留敏感数据的所有权，通过缓解与隐私相关的担忧，使用公共或混合云部署模型实现规模和效率，并在边缘部署人工智能推理。



== 环境情报

在环境危害领域，各行各业可以多种方式利用地理空间分析。政府和公共工程部门可以就公共卫生和天气状况获得可行的见解，以便在流行病或野火等自然灾害期间更好地为公众提供建议。例如，您可以在公共场所（例如机场或医院）识别 COVID 阳性患者，而不会损害受影响个人的隐私，并提醒相关部门和附近公众采取必要的安全措施。



== 边缘设备可穿戴设备

在军事和战场上，您可以使用边缘 AI 推理作为可穿戴设备来跟踪士兵的健康状况、监控驾驶员行为并向当局发出接近军用车辆的安全和相关风险警报，同时保护士兵的隐私。军队的未来将走向高科技，战场物联网 (IoBT) 和军事物联网 (IoMT) 将应用于可穿戴作战装备，帮助士兵通过使用快速边缘计算识别敌人并在战斗中表现得更好。保护和保存从无人机和可穿戴设备等边缘设备收集的视觉数据对于阻止黑客和敌人至关重要。



== 非战斗人员撤离行动

非战斗人员撤离行动 (NEO) 由国防部执行，旨在协助将生命受到威胁的美国公民和国民、国防部文职人员以及指定人员（东道国 (HN) 和第三国国民 (TCN)）撤离到适当的安全避难所。现有的行政控制措施主要采用手动的撤离人员筛选流程。然而，通过使用高度自动化的 AI/ML 工具结合 AI/ML 视频混淆技术，可以提高撤离人员识别、撤离人员跟踪和威胁筛查的准确性、安全性和速度。



== 医疗保健和生物医学研究

图像处理用于根据计算机断层扫描 (CT) 或磁共振成像 (MRI) 获得的 3D 图像诊断手术规划的病理。 HIPAA 隐私规则规定了组织如何收集、处理和删除所有个人信息和照片等数字图像。根据 HIPAA 安全港规定，要使数据符合可共享条件，必须删除正面照片和任何类似图像。用于从结构 CT/MR 图像中隐藏个人面部特征的去识别或颅骨剥离算法等自动化技术已成为生物医学研究机构数据共享过程的重要组成部分。



== AI/ML分析的云迁移

企业客户传统上在本地训练和部署 AI/ML 模型。出于规模经济和效率的原因，这些客户正在扩展以将 AI/ML 功能转移到公共、混合或多云部署中。然而，它们受到可以向其他基础设施公开的数据的限制。  NetApp解决方案可应对各种网络安全威胁， https://www.netapp.com/data-protection/?internal_promo=mdw_aiml_ww_all_awareness-coas_blog["数据保护"^]和安全评估，并与 Protopia 数据转换相结合，最大限度地降低将图像处理 AI/ML 工作负载迁移到云端所带来的风险。

有关其他行业的边缘计算和 AI 推理的更多用例，请参阅link:../infra/ai-lenovo-edge-intro.html["TR-4886 边缘人工智能推理"^]以及NetApp AI 博客， https://www.netapp.com/blog/federated-learning-intelligence-vs-privacy/["情报与隐私"^] 。
