---
sidebar: sidebar 
permalink: software/ai-conf-protopia-conclusion.html 
keywords: conclusion, ai inferencing, 
summary: 数据有三种状态 - 静止、传输和计算。任何人工智能推理服务的一个重要部分应该是在整个过程中保护数据免受威胁。在推理过程中保护数据至关重要，因为该过程可能会暴露有关外部客户和提供推理服务的企业的私人信息。 
---
= 结束语
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
数据有三种状态：静止、传输和计算。任何人工智能推理服务的一个重要部分应该是在整个过程中保护数据免受威胁。在推理过程中保护数据至关重要，因为该过程可能会暴露有关外部客户和提供推理服务的企业的私人信息。 Protopia AI 是当今市场上用于机密 AI 推理的非侵入式纯软件解决方案。借助 Protopia，AI 仅接收数据记录中对于执行手头的 AI/ML 任务至关重要的转换信息，仅此而已。这种随机变换不是一种掩蔽形式，而是基于通过使用精心策划的噪声以数学方式改变数据的表示。

具有ONTAP功能的NetApp存储系统可提供与本地 SSD 存储相同或更佳的性能，并且与NetApp DataOps Toolkit 结合使用，可为数据科学家、数据工程师、AI/ML 开发人员以及业务或企业 IT 决策者带来以下优势：

* 在人工智能系统、分析系统和其他关键业务系统之间轻松共享数据。这种数据共享减少了基础设施开销，提高了性能，并简化了整个企业的数据管理。
* 独立可扩展的计算和存储，以最大限度地降低成本并提高资源利用率。
* 使用集成的 Snapshot 副本和克隆来简化开发和部署工作流程，以实现即时且节省空间的用户工作区、集成版本控制和自动部署。
* 针对灾难恢复、业务连续性和监管要求的企业级数据保护和数据治理。
* 简化数据管理操作的调用；从 Jupyter 笔记本中的NetApp DataOps Toolkit 快速获取数据科学家工作区的 Snapshot 副本以进行备份和追溯。


NetApp和 Protopia 解决方案提供了灵活的横向扩展架构，非常适合企业级 AI 推理部署。它可以实现数据保护并为敏感信息提供隐私，其中机密的 AI 推理要求可以通过内部部署和混合云部署中的负责任的 AI 实践来满足。
