---
sidebar: sidebar 
permalink: software/ai-hybrid-ddlnexus-setup.html 
keywords: NetApp AI, AI, Artificial Intelligence, ML, Machine Learning, NVIDIA, Hybrid, Hybrid Cloud, Hybrid Multicloud, Cloud, AWS, Amazon, Amazon Web Services, FSx ONTAP, FSx, NetApp ONTAP, FlexCache, SnapMirror, BlueXP 
summary: 采用 Domino Data Lab 和NetApp 的混合多云 MLOps - 初始设置 
---
= 初始设置
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
本节介绍在包含本地数据中心和 AWS 的混合环境中使用 Domino Nexus 和NetApp数据服务所需执行的初始设置任务。



== 前提条件

在执行本节中概述的步骤之前，我们假设您已经执行了以下任务：

* 您已经部署并配置了内部部署NetApp ONTAP存储平台。欲了解更多信息，请参阅link:https://www.netapp.com/support-and-training/documentation/["NetApp产品文档"] 。
* 您已在 AWS 中配置了Amazon FSx ONTAP实例。欲了解更多信息，请参阅link:https://aws.amazon.com/fsx/netapp-ontap/["Amazon FSx ONTAP产品页面"] 。
* 您已经在本地数据中心配置了 Kubernetes 集群。欲了解更多信息，请参阅link:https://docs.dominodatalab.com/en/latest/admin_guide/b35e66/admin-guide/["Domino 管理指南"] 。
* 您已在 AWS 中配置了 Amazon EKS 集群。欲了解更多信息，请参阅link:https://docs.dominodatalab.com/en/latest/admin_guide/b35e66/admin-guide/["Domino 管理指南"] 。
* 您已在本地 Kubernetes 集群中安装了NetApp Trident 。此外，您已配置此Trident实例以在配置和管理存储资源时使用您的内部NetApp ONTAP存储平台。欲了解更多信息，请参阅link:https://docs.netapp.com/us-en/trident/index.html["NetApp Trident文档"] 。
* 您已在 Amazon EKS 集群中安装了NetApp Trident 。此外，您已配置此Trident实例以在配置和管理存储资源时使用您的Amazon FSx ONTAP实例。欲了解更多信息，请参阅link:https://docs.netapp.com/us-en/trident/index.html["NetApp Trident文档"] 。
* 您的本地数据中心和 AWS 中的虚拟私有云 (VPC) 之间必须具有双向网络连接。有关实现此目的的各种选项的更多详细信息，请参阅link:https://docs.aws.amazon.com/vpc/latest/userguide/vpn-connections.html["Amazon 虚拟专用网络 (VPN) 文档"]。




== 在 AWS 中安装 Domino Enterprise AI 平台

要在 AWS 中安装 Domino Enterprise MLOps 平台，请按照link:https://docs.dominodatalab.com/en/latest/admin_guide/c1eec3/deploy-domino/["Domino 管理指南"]。您必须在之前配置的同一 Amazon EKS 集群中部署 Domino。此外，必须已经在此 EKS 集群中安装和配置NetApp Trident ，并且您必须在 domino.yml 安装配置文件中指定 Trident 管理的存储类作为共享存储类。


NOTE: 请参阅link:https://docs.dominodatalab.com/en/latest/admin_guide/7f4331/install-configuration-reference/#storage-classes["Domino 安装配置参考指南"]有关如何在 domino.yml 安装配置文件中指定共享存储类的详细信息。


NOTE: link:https://www.netapp.com/media/79922-tr-4952.pdf["技术报告 TR-4952"]介绍如何使用Amazon FSx ONTAP在 AWS 中部署 Domino，这可以作为解决出现的任何问题的有用参考。



== 启用 Domino Nexus

接下来，您必须启用 Domino Nexus。请参阅link:https://docs.dominodatalab.com/en/latest/admin_guide/c65074/nexus-hybrid-architecture/["Domino 管理指南"]了解详情。



== 在本地数据中心部署 Domino 数据平面

接下来，您必须在本地数据中心部署 Domino 数据平面。您必须在之前配置的本地 Kubernetes 集群中部署此数据平面。此外，必须已经在此 Kubernetes 集群中安装并配置了NetApp Trident 。请参阅link:https://docs.dominodatalab.com/en/latest/admin_guide/5781ea/data-planes/["Domino 管理指南"]了解详情。
