---
sidebar: sidebar 
permalink: software/ai-osmlops-trident-ops.html 
keywords: Trident 
summary: NetApp的开源 MLOps - Trident操作示例 
---
= Trident操作示例
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
本节包含您可能想要使用Trident执行的各种操作的示例。



== 导入现有卷

如果您的NetApp存储系统/平台上存在现有卷，并且您想要将其安装在 Kubernetes 集群内的容器上，但这些卷未与集群中的 PVC 绑定，则必须导入这些卷。您可以使用Trident卷导入功能来导入这些卷。

以下示例命令显示导入名为 `pb_fg_all`。有关 PVC 的更多信息，请参阅 https://kubernetes.io/docs/concepts/storage/persistent-volumes/["Kubernetes 官方文档"^]。有关卷导入功能的更多信息，请参阅 https://docs.netapp.com/us-en/trident/index.html["Trident文档"^]。

一个 `accessModes`的价值 `ReadOnlyMany`在示例 PVC 规范文件中指定。有关 `accessMode`字段，请参阅 https://kubernetes.io/docs/concepts/storage/persistent-volumes/["Kubernetes 官方文档"^]。

....
$ cat << EOF > ./pvc-import-pb_fg_all-iface1.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pb-fg-all-iface1
  namespace: default
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: ontap-ai-flexgroups-retain-iface1
EOF
$ tridentctl import volume ontap-ai-flexgroups-iface1 pb_fg_all -f ./pvc-import-pb_fg_all-iface1.yaml -n trident
+--------------------------------+--------+-----------------------------------+----------+--------------------------------------------+--------+---------+
|          NAME                  |  SIZE  |       STORAGE CLASS               | PROTOCOL |             BACKEND UUID                         | STATE  | MANAGED |
+--------------------------------+--------+-----------------------------------+----------+------------------------------------------+--------+---------+
| default-pb-fg-all-iface1-7d9f1 | 10 TiB | ontap-ai-flexgroups-retain-iface1 | file     | b74cbddb-e0b8-40b7-b263-b6da6dec0bdd | online | true    |
+--------------------------------+--------+-----------------------------------+----------+--------------------------------------------+--------+---------+
$ tridentctl get volume -n trident
+----------------------------------+---------+-----------------------------------+----------+--------------------------------------+--------+---------+
|               NAME               |  SIZE   |           STORAGE CLASS           | PROTOCOL |             BACKEND UUID             | STATE  | MANAGED |
+----------------------------------+---------+-----------------------------------+----------+--------------------------------------+--------+---------+
| default-pb-fg-all-iface1-7d9f1   | 10 TiB  | ontap-ai-flexgroups-retain-iface1 | file     | b74cbddb-e0b8-40b7-b263-b6da6dec0bdd | online | true    |
+----------------------------------+---------+-----------------------------------+----------+--------------------------------------+--------+---------+
$ kubectl get pvc
NAME                 STATUS   VOLUME                             CAPACITY         ACCESS MODES   STORAGECLASS                        AGE
pb-fg-all-iface1     Bound    default-pb-fg-all-iface1-7d9f1     10995116277760   ROX            ontap-ai-flexgroups-retain-iface1   25h
....


== 提供新卷

您可以使用Trident在NetApp存储系统或平台上配置新卷。



=== 使用 kubectl 配置新卷

以下示例命令显示使用 kubectl 配置新的FlexVol volume。

一个 `accessModes`的价值 `ReadWriteMany`在下面的示例 PVC 定义文件中指定。有关 `accessMode`字段，请参阅 https://kubernetes.io/docs/concepts/storage/persistent-volumes/["Kubernetes 官方文档"^]。

....
$ cat << EOF > ./pvc-tensorflow-results.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: tensorflow-results
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ontap-ai-flexvols-retain
EOF
$ kubectl create -f ./pvc-tensorflow-results.yaml
persistentvolumeclaim/tensorflow-results created
$ kubectl get pvc
NAME                              STATUS    VOLUME                             CAPACITY         ACCESS MODES   STORAGECLASS                        AGE
pb-fg-all-iface1                  Bound     default-pb-fg-all-iface1-7d9f1     10995116277760   ROX            ontap-ai-flexgroups-retain-iface1   26h
tensorflow-results                Bound     default-tensorflow-results-2fd60   1073741824       RWX            ontap-ai-flexvols-retain            25h
....


=== 使用NetApp DataOps 工具包配置新卷

您还可以使用NetApp DataOps Toolkit for Kubernetes 在NetApp存储系统或平台上配置新卷。 NetApp DataOps Toolkit for Kubernetes 利用Trident来配置卷，但简化了用户的流程。请参阅link:https://github.com/NetApp/netapp-dataops-toolkit/blob/main/netapp_dataops_k8s/docs/volume_management.md["文档"]了解详情。
